services:
  api:
    build:
      context: .
      dockerfile: src/server/Dockerfile.dev
    container_name: fastapi_dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: src/client/Dockerfile.dev
    container_name: nextjs_dev
    volumes:
      - ./src/client:/app
      - /app/node_modules  # Prevent host-node_modules conflicts
    ports:
      - "3000:3000"