services:
  db:
    build: ./src/db
    container_name: db_c
    env_file: [.env]
    ports:
      - "5432:5432"
    networks:
      - backend

  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: server_c
    env_file: [.env]
    depends_on:
      - db
    networks:
      - backend

  client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: client_c
    env_file: [.env]
    depends_on:
      - server
    networks:
      - backend

  nginx:
    build:
      context: ./src/nginx
      dockerfile: Dockerfile
    container_name: nginx_c
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - client
      - server
    networks:
      - backend

networks:
  backend:
    driver: bridge