services:
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile.dev
    container_name: server_dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: src/client/Dockerfile.dev
    container_name: client_dev
    volumes:
      - ./src/client:/app
      - /app/node_modules  # Prevent host-node_modules conflicts
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./src/nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"