services:
  db:
    build: ./src/db
    container_name: db_c
    env_file: [.env]
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: fastapi_c
    env_file: [.env]
    depends_on:
      - db
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: nextjs_c
    env_file: [.env]
    depends_on:
      - api
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_c
    ports:
      - "80:80"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - api
    networks:
      - backend

networks:
  backend:
    driver: bridge