services:
  db:
    build: ./src/db
    container_name: db_c
    env_file: [.env]
    ports:
      - "5432:5432"
    networks:
      - backend

  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: server_c
    env_file: [.env]
    depends_on:
      - db
    networks:
      - backend

  test:
    build:
      context: .
      dockerfile: tests/Dockerfile.test
    container_name: tests_c
    env_file: [.env]
    depends_on:
      - db
      - server
    networks:
      - backend
    command: ["./run_tests.bash"]
    # Optional: Mount coverage output
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./coverage:/app/htmlcov

networks:
  backend:
    driver: bridge