FROM python:3.11-bullseye

# Install Java 21
RUN apt-get update && \
    apt-get install -y wget gnupg2 software-properties-common && \
    wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | \
    gpg --dearmor -o /usr/share/keyrings/docker.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/docker.gpg] https://packages.adoptium.net/artifactory/deb bullseye main" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y temurin-21-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/temurin-21-jdk

WORKDIR /app

# Copy .env from root into container
COPY .env .

COPY setup.py .
COPY src/ ./src
COPY tests/ ./tests

RUN pip install --no-cache-dir -r ./src/server/requirements.txt

ENV PYTHONPATH=/app

COPY tests/run_tests.bash ./run_tests.bash
RUN chmod +x run_tests.bash

CMD ["./run_tests.bash"]